### ISSUE TITLE
Migrating from Timecop to ActiveSupport time travel

### ISSUE THREAD

**Issue by brain-geek** [kevin-j-m/clockwork-test#27]
For quite some time, active support has had support for the same functionality Timecop provides.

Furthermore, this project already has dependency on AS, as clockwork is [dependent on it](https://github.com/Rykian/clockwork/blob/master/clockwork.gemspec#L21).

Would it make sense to remove this dependency?

Also, this will require major release afterwards.

**Comment by kevin-j-m** [comment]
Good question/suggestion which I don't have an entirely satisfying answer for how to proceed. I'm a fan of ActiveSupport's `travel_to` features and use them in my new rails projects.

ActiveSupport is currently a dev dependency of the project (for ease of test writing), but is not part of the dependencies for the gem proper.

However, it's unclear to me what the future of clockwork's relationship with ActiveSupport is. It was [removed](https://github.com/Rykian/clockwork/pull/18), but that was then [reverted](https://github.com/Rykian/clockwork/pull/41). I'm not sure if there's still appetite to remove ActiveSupport.

That said, we could have AS as a dependency and if users want to use this gem, then they'll have pulled in AS by using this, whether or not clockwork includes it. I wonder if keeping Timecop helps in having a smaller library targeted towards a specific problem, rather than pulling in all of AS for this one feature of it. 

What do you think?

**Comment by brain-geek** [comment]
Yeah, it's a good question. If/when clockwork removes AS dependency, it would be a bad idea to have it in this project, as it's too big dependency to have.

One other thing to consider: it feels like Rubocop is more dead than alive. Even [deprecation-fix PRs](https://github.com/travisjeffery/timecop/pull/215) from 6+ month ago are not merged . While it works now, it may break. For example, Ruby 2.4 time objects have timezone-related changes, so it may function incorrectly.

**Comment by kevin-j-m** [comment]
I'm certainly wary of dependencies and the affects they may have in your library, and should we start to see issues with Timecop, then I'm much more motivated to consider alternatives (of which, the only one I'm aware of that still has any traction or use would be AS).

However, at this time, I'm concerned that this may be trying to solve a problem that we don't have right now, and our time may be better spent in other ways. Do you think that's a fair assessment?

**Comment by brain-geek** [comment]
This decision is up to you - and at the moment this may be a bit too early - Timecop is still good.

Thanks for discussing this anyway! 😄
